# Generated by Django 4.2.5 on 2023-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
        ),
    ]
